/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MiContrato } from "./MiContrato";
export * as factories from "./factories";
export { MiContrato__factory } from "./factories/MiContrato__factory";
