/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MiContratoInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cambiarNombre"
      | "historialSize"
      | "obtenerCambios"
      | "obtenerHistorial"
      | "obtenerNombre"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "NombreCambiado"): EventFragment;

  encodeFunctionData(
    functionFragment: "cambiarNombre",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "historialSize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "obtenerCambios",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "obtenerHistorial",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "obtenerNombre",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "cambiarNombre",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "historialSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "obtenerCambios",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "obtenerHistorial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "obtenerNombre",
    data: BytesLike
  ): Result;
}

export namespace NombreCambiadoEvent {
  export type InputTuple = [
    nuevoNombre: string,
    cambiador: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    nuevoNombre: string,
    cambiador: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    nuevoNombre: string;
    cambiador: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MiContrato extends BaseContract {
  connect(runner?: ContractRunner | null): MiContrato;
  waitForDeployment(): Promise<this>;

  interface: MiContratoInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cambiarNombre: TypedContractMethod<
    [nuevoNombre: string],
    [void],
    "nonpayable"
  >;

  historialSize: TypedContractMethod<[], [bigint], "view">;

  obtenerCambios: TypedContractMethod<[], [bigint], "view">;

  obtenerHistorial: TypedContractMethod<[], [string[]], "view">;

  obtenerNombre: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cambiarNombre"
  ): TypedContractMethod<[nuevoNombre: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "historialSize"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "obtenerCambios"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "obtenerHistorial"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "obtenerNombre"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "NombreCambiado"
  ): TypedContractEvent<
    NombreCambiadoEvent.InputTuple,
    NombreCambiadoEvent.OutputTuple,
    NombreCambiadoEvent.OutputObject
  >;

  filters: {
    "NombreCambiado(string,address,uint256)": TypedContractEvent<
      NombreCambiadoEvent.InputTuple,
      NombreCambiadoEvent.OutputTuple,
      NombreCambiadoEvent.OutputObject
    >;
    NombreCambiado: TypedContractEvent<
      NombreCambiadoEvent.InputTuple,
      NombreCambiadoEvent.OutputTuple,
      NombreCambiadoEvent.OutputObject
    >;
  };
}
